name: flutter_connectivity_service
description: A comprehensive Flutter package for managing network connectivity with real-time monitoring, automatic reconnection, and user-friendly snackbar notifications.
version: 2.0.1
homepage: https://github.com/mr-sahu/flutter_connectivity_service

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true